server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taegukair
    username: taegukair
    password: taegukair
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/imgs/
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  config:
    import: optional:classpath:coolsms.properties

jwt:
  secret: q+hXD1LywTnxIvzJNXVlMVvms/PylZZgDTGlexM8BF2rRewM6QbkAdQUyOa1DiXzjui5wLitTd+2u9EjKzbRjg==

springdoc:
  swagger-ui:
    path: /swagger-ui.html

image:
  add-resource-locations: classpath:/static/imgs/
  add-resource-handler: /imgs/**
  image-dir: src/main/resources/static/imgs
  image-url: http://localhost:8080/imgs/

logging:
  level:
    root: info


